spring:
  application:
    name: plog
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/plog?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PWD}
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
minio:
  enabled: ${MINIO_ENABLED:false}
  endpoint: ${MINIO_ENDPOINT}
  access_key: ${MINIO_ACCESS_KEY}
  secret_key: ${MINIO_SECRET_KEY}
  bucket: team-bucket
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
custom:
  jwt:
    secretKey: ${SECRET_KEY}
    access-expiration: 1800000 # 30분
    refresh-expiration: 3153600000000 # 약 100년
  cookie:
    domain: ${COOKIE_DOMAIN:localhost}
    secure: ${COOKIE_SECURE:false}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}